name: make-lint

on:
  push:
    branches:
      - '**'
    tags:
      - '**'

jobs:
  my-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: make install
      - run: make lint
